### ISSUE TITLE
Any possiblity for an example that uses a complex model

### ISSUE THREAD

**Issue by bjarnik** [janno-p/XRoadLib#14]
Is there any possibility of getting an example of how you would use this to return a complex object?

As an example, returning a object of the following form:

```
public class ComplexObect
{
    public ComplexPerson Child { get; set; }
    public ComplexPerson Uncle { get; set; }
}

public class ComplexPerson
{
    public ComplexKey Key { get; set; }
    public string Name { get; set; }
    public int Age { get; set; }
}

public class ComplexKey
{
    public int Key { get; set; }
    public int ReferenceKey { get; set; }
}
```

**Comment by bjarnik** [comment]
Nevermind, I figured it out.
I wasn't using XRoadSerializable the way it's meant to.
Seems to work now.

**Comment by janno-p** [comment]
At the moment it's required to have XRoadSerializable type as a root type somewhere in the type hierarchy. I have thought about removing that requirement to simplify models, but haven't got to that yet.
