### ISSUE TITLE
How to get memberCode in my service?

### ISSUE THREAD

**Issue by nigr0nyx** [janno-p/XRoadLib#21]
Hi guys! 
Is it possible, get memberCode and other client information in my service?

**Comment by janno-p** [comment]
Hi! I have thought about including header information in service interface, but haven't got to implementing it.

At the moment, if you're using AspNetCore package you could use IWebServiceContextAccessor through dependency injection. From that accessor you can access header information `webServiceContextAccessor.WebServiceContext.Request.Header` which should include Client info. Header is of ISoapHeader type, but for X-Road requests it can be matched against XRoadHeader type.

**Comment by nigr0nyx** [comment]
Thanks! Today I even realized through method you described 👍
